from typing import Protocol
from uuid import UUID

from qdrant_bench.domain.entities.core import Connection, Dataset, Experiment, ObjectStorage, Run


class ExperimentRepository(Protocol):
    async def save(self, experiment: Experiment) -> Experiment: ...
    async def get(self, id: UUID) -> Experiment | None: ...
    async def list(self) -> list[Experiment]: ...


class RunRepository(Protocol):
    async def save(self, run: Run) -> Run: ...
    async def get(self, id: UUID) -> Run | None: ...
    async def list(self, experiment_id: UUID | None = None, status: str | None = None) -> list[Run]: ...


class DatasetRepository(Protocol):
    async def save(self, dataset: Dataset) -> Dataset: ...
    async def get(self, id: UUID) -> Dataset | None: ...
    async def list(self) -> list[Dataset]: ...


class ConnectionRepository(Protocol):
    async def save(self, connection: Connection) -> Connection: ...
    async def get(self, id: UUID) -> Connection | None: ...
    async def list(self) -> list[Connection]: ...


class ObjectStorageRepository(Protocol):
    async def save(self, storage: ObjectStorage) -> ObjectStorage: ...
    async def list(self) -> list[ObjectStorage]: ...
