from typing import Protocol, List, Optional
from uuid import UUID
from qdrant_bench.domain.entities.core import Experiment, Run, Dataset, Connection, ObjectStorage

class ExperimentRepository(Protocol):
    async def save(self, experiment: Experiment) -> Experiment:
        ...
    async def get(self, id: UUID) -> Optional[Experiment]:
        ...
    async def list(self) -> List[Experiment]:
        ...

class RunRepository(Protocol):
    async def save(self, run: Run) -> Run:
        ...
    async def get(self, id: UUID) -> Optional[Run]:
        ...
    async def list(self, experiment_id: Optional[UUID] = None, status: Optional[str] = None) -> List[Run]:
        ...

class DatasetRepository(Protocol):
    async def save(self, dataset: Dataset) -> Dataset:
        ...
    async def get(self, id: UUID) -> Optional[Dataset]:
        ...
    async def list(self) -> List[Dataset]:
        ...

class ConnectionRepository(Protocol):
    async def save(self, connection: Connection) -> Connection:
        ...
    async def list(self) -> List[Connection]:
        ...

class ObjectStorageRepository(Protocol):
    async def save(self, storage: ObjectStorage) -> ObjectStorage:
        ...
    async def list(self) -> List[ObjectStorage]:
        ...

